// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class COTIZACION
{
    public int COTZID { get; set; }

    public string IDENTIFICACION { get; set; }

    public DateTime? FECHA { get; set; }

    public string ESTADO { get; set; }

    public virtual ICollection<COTIZACION_DETALLE> COTIZACION_DETALLE { get; set; } = new List<COTIZACION_DETALLE>();

    public virtual CLIENTE IDENTIFICACIONNavigation { get; set; }
}