// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class INVENTARIO
{
    public int PRODUCTID { get; set; }

    public int? STOCK { get; set; }

    public string UBICACION { get; set; }

    public virtual ICollection<COTIZACION_DETALLE> COTIZACION_DETALLE { get; set; } = new List<COTIZACION_DETALLE>();

    public virtual PRODUCTO PRODUCTO { get; set; }
}