// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class PRODUCTO
{
    public int PRODUCTID { get; set; }

    public string NOMBRE { get; set; }

    public string DESCRIPCION { get; set; }

    public string SKU { get; set; }

    public string UNIDAMEDIDA { get; set; }

    public virtual ICollection<PRECIOPRODUCTO> PRECIOPRODUCTO { get; set; } = new List<PRECIOPRODUCTO>();

    public virtual INVENTARIO PRODUCT { get; set; }
}