// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class REPARTIDOR
{
    public int REPARID { get; set; }

    public string ESTADO { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public virtual ICollection<RUTA> RUTA { get; set; } = new List<RUTA>();

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();
}