// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class RUTA
{
    public int RUTAID { get; set; }

    public int? REPARID { get; set; }

    public string NOMBRERUTA { get; set; }

    public DateTime? FECHASADICION { get; set; }

    public string ESTADO { get; set; }

    public virtual REPARTIDOR REPAR { get; set; }

    public virtual ICollection<UBICACION_ENTREGA> UBICACION_ENTREGA { get; set; } = new List<UBICACION_ENTREGA>();
}