// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class UBICACION_ENTREGA
{
    public int UBIID { get; set; }

    public int? RUTAID { get; set; }

    public string DIRECCION { get; set; }

    public decimal? LATITUD { get; set; }

    public decimal? LONGITUD { get; set; }

    public string ESTADO { get; set; }

    public virtual RUTA RUTA { get; set; }
}