// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class USUARIO
{
    public int USERID { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO { get; set; }

    public string ROL { get; set; }

    public string EMAIL { get; set; }

    public string PASSWORD { get; set; }

    public bool? ESTADO { get; set; }

    public string ATTRIBUTE_8 { get; set; }
}