// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DulceFacil.Infraestructura.AccesoDatos;

public partial class VENTA
{
    public int VENTAID { get; set; }

    public int? REPARID { get; set; }

    public DateTime? FECHA { get; set; }

    public decimal? TOTAL { get; set; }

    public virtual ICollection<COTIZACION_DETALLE> COTIZACION_DETALLE { get; set; } = new List<COTIZACION_DETALLE>();

    public virtual REPARTIDOR REPAR { get; set; }
}